import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const info = api.info.hello.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#0C0A00]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            www.forrestdevelops.com
          </h1>
          <p className="text-2xl text-white">
            {info.data ? info.data.map(info =>
              <a href={info.url} key={info.id}>{info.name}</a>) : "Loading Resources..."}
          </p>
            <Link href="/beer" legacyBehavior>
                <a className="text-2xl text-white">Reviewed Beers</a>
            </Link>
            <Link href="/recipe" legacyBehavior>
                <a className="text-2xl text-white">Recipes</a>
            </Link>
        </div>
      </main >
    </>
  );
}
